apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opsimate.fullname" . }}-worker
  labels:
    {{- include "opsimate.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "opsimate.worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "opsimate.worker.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          command: ["node", "apps/server/dist/worker.js"]
          env:
            - name: NODE_ENV
              value: {{ .Values.env.nodeEnv }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: /app/data/database
              subPath: database
            - name: data
              mountPath: /app/data/private-keys
              subPath: private-keys
            {{- end }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "opsimate.fullname" . }}-data
        {{- end }}