apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opsimate.fullname" . }}-secret
  labels:
    {{- include "opsimate.labels" . | nindent 4 }}
type: Opaque
stringData:
  API_TOKEN: {{ .Values.env.apiToken }}