apiVersion: v1
kind: Service
metadata:
  name: {{ include "opsimate.backend.serviceName" . }}
  labels:
    {{- include "opsimate.backend.labels" . | nindent 4 }}
spec:
<<<<<<< Updated upstream
  type: {{ .Values.service.backend.type }}
=======
  type: {{ .Values.service.type }}
>>>>>>> Stashed changes
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "opsimate.backend.selectorLabels" . | nindent 4 }}