apiVersion: v1
kind: Service
metadata:
  name: {{ include "opsimate.fullname" . }}-frontend
  labels:
    {{- include "opsimate.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.port }}
  selector:
    {{- include "opsimate.frontend.selectorLabels" . | nindent 4 }}