apiVersion: v1
kind: Service
metadata:
  name: {{ include "opsimate.fullname" . }}-backend
  labels:
    {{- include "opsimate.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
  selector:
    {{- include "opsimate.backend.selectorLabels" . | nindent 4 }}